/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  PokemonListItem,
} from './utils/models/pokemon-list';

export namespace Components {
  interface PokemonDetail {
    'data': PokemonListItem;
  }
  interface PokemonList {}
}

declare global {


  interface HTMLPokemonDetailElement extends Components.PokemonDetail, HTMLStencilElement {}
  var HTMLPokemonDetailElement: {
    prototype: HTMLPokemonDetailElement;
    new (): HTMLPokemonDetailElement;
  };

  interface HTMLPokemonListElement extends Components.PokemonList, HTMLStencilElement {}
  var HTMLPokemonListElement: {
    prototype: HTMLPokemonListElement;
    new (): HTMLPokemonListElement;
  };
  interface HTMLElementTagNameMap {
    'pokemon-detail': HTMLPokemonDetailElement;
    'pokemon-list': HTMLPokemonListElement;
  }
}

declare namespace LocalJSX {
  interface PokemonDetail {
    'data'?: PokemonListItem;
  }
  interface PokemonList {}

  interface IntrinsicElements {
    'pokemon-detail': PokemonDetail;
    'pokemon-list': PokemonList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pokemon-detail': LocalJSX.PokemonDetail & JSXBase.HTMLAttributes<HTMLPokemonDetailElement>;
      'pokemon-list': LocalJSX.PokemonList & JSXBase.HTMLAttributes<HTMLPokemonListElement>;
    }
  }
}


